# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-demultiplex-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::markdown=3.3.4
  - conda-forge::pygments=2.9.0
  - conda-forge::pymdown-extensions=8.2
  - conda-forge::python=3.9.4
  - conda-forge::r-base=4.1.0
  - conda-forge::r-essentials=4.0
  - bioconda::bismark=0.23.0
  - bioconda::bowtie2=2.4.4
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.10.1
  - bioconda::perl-gdgraph
  - bioconda::samtools=1.12
