# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-demultiplex-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::markdown=3.1.1
  - conda-forge::pygments=2.5.2
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::python=3.7.3
  - conda-forge::r-base=3.5.1
  - conda-forge::r-essentials=3.5.1
  - bioconda::bismark=0.22.1
  - bioconda::bowtie2=2.3.5.1
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.9
  - bioconda::perl-gdgraph
  - bioconda::samtools=1.10
  - bioconda::skewer=0.2.2
